image: node:lts-alpine

stages: # List of stages for jobs, and their order of execution
    - install
    - build
    - quality
    - deploy

# Installation job script for front and backend
default:
    tags:
        - nodejs
    cache:
        - key:
          paths:
              - frontend/.npm/
              - backend/.npm/

    before_script:
        - cd frontend
        - npm ci --cache .npm -prefer-offline
        - cd ../backend
        - npm ci --cache .npm -prefer-offline
        - cd ..

frontend:build:
    stage: build
    tags:
        - nodejs
    script:
        - cd frontend
        - echo "Building frontend..."
        - npm run build
        - echo "Frontend build complete."
        - cd ..

backend:build:
    stage: build
    tags:
        - nodejs
    script:
        - cd backend
        - echo "Building backend..."
        - npm run build
        - echo "Backend build complete."
        - cd ..

frontend:lint:
    stage: quality
    tags:
        - nodejs
    script:
        - cd frontend
        - npm run lint
        - echo "No lint issues found."
        - cd ..

backend:lint:
    stage: quality
    tags:
        - nodejs
    script:
        - cd backend
        - npm run lint
        - echo "No lint issues found."
        - cd ..

frontend:test:unit:
    stage: quality
    tags:
        - nodejs
    script:
        - echo "Start frontend test..."
        - cd frontend
        - echo "Add Vitest test execution here"
        - cd ..
        - echo "Frontend test succeeded."

backend:test:unit:
    stage: quality
    tags:
        - nodejs
    script:
        - echo "Start backend test..."
        - cd backend
        - echo "Add backend test execution here"
        - cd ..
        - echo "Frontend test succeeded."

deploy:
    stage: deploy
    tags:
        - docker
        - nodejs
    environment: production
    script:
        - echo "Deploying application..."
        - echo "Add deployment here"
        - echo "Application successfully deployed."
    when: manual