version: "3"

services:
  
    backend:
        image: mmis-gui-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            # Data and assets folders
            - CORS_ORIGIN_DOCKER=http://localhost:8080
            - PORT=3000
            - WS_ADDRESS=0.0.0.0
            - WS_PORT=3030

            - DATA=data
            - MODELS=assets/models
            - MATERIALS=assets/materials

            # Log configuration
            - LOG_FILE=backend.log
            - LOG_LEVEL=info
        volumes:
            - ./backend/data:/usr/src/app/data
            - ./backend/assets:/usr/src/app/assets
        ports:
            # Don't change 3000 host port as it can't be dynamically changed in the frontend container
            - 3000:3000
            - 3030:3030
        networks:
            - backend

    frontend:
        image: mmis-gui-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            # Don't change the API url as it can't be dynamically changed in the frontend container without rebuilding
            - VITE_API_BASE_URL=http://localhost:3000/api
            - VITE_STATIC_MODE=false
            - VITE_BASE_PATH=""
            - VITE_DEFAULT_PDT="demo_pdt"
        ports:
            - 8080:80
        networks:
            - frontend
            - backend

    nginx:
        image: nginx:alpine
        container_name: nginx-app
        volumes:
        - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
        - 80:80
        depends_on:
        - frontend
       
       
networks:
    frontend:
    backend:
